language: ruby
rvm:
  - 1.9.3
  - 2.0.0
bundler_args: "--without development"
before_install:
  - gem install bundler --pre
before_script:
  - "cp config/database.yml.example config/database.yml"
  - RAILS_ENV=test bundle exec rake db:create db:migrate
script: true
